apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - name: ngnix
        image: ngnix:1.7.9
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
